// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use bigdecimal::BigDecimal;
use chrono::{DateTime, Utc};
use diesel::{AsChangeset, Identifiable, Queryable, Selectable};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Queryable, Debug, Identifiable, Selectable)]
#[diesel(table_name = crate::schema::groups)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Group {
    pub id: i64,
    pub name: String,
    pub remark: Option<String>,
    pub update_time: Option<DateTime<Utc>>,
    pub create_time: DateTime<Utc>,
    pub create_by: i64,
    pub update_by: Option<i64>,
    pub is_delete: bool,
}

#[derive(Queryable, Debug, Identifiable, Selectable)]
#[diesel(primary_key(group_id, permission_id))]
#[diesel(table_name = crate::schema::groups_permissions)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct GroupsPermission {
    pub group_id: i64,
    pub permission_id: i64,
}

#[derive(Queryable, Debug, Clone, Eq, PartialEq, Hash, Selectable)]
#[diesel(table_name = crate::schema::permissions)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Permission {
    pub id: i64,
    pub name: String,
    pub remark: Option<String>,
    pub update_time: Option<DateTime<Utc>>,
    pub create_time: DateTime<Utc>,
    pub create_by: i64,
    pub update_by: Option<i64>,
    pub is_delete: bool,
}

#[derive(Queryable, Clone, Serialize, Deserialize, Selectable, JsonSchema, Default,AsChangeset)]
#[diesel(table_name = crate::schema::users)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct User {
    pub id: i64,
    pub username: String,
    pub password: String,
    pub group_id: i64,
    pub tenantry: String,
    pub remark: Option<String>,
    pub update_time: Option<DateTime<Utc>>,
    pub create_time: DateTime<Utc>,
    pub create_by: i64,
    pub update_by: Option<i64>,
    pub is_delete: bool,
}

#[derive(Queryable, Clone, Serialize, Deserialize, Selectable, JsonSchema, Default,AsChangeset)]
#[diesel(table_name = crate::schema::auction)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Auction {
    pub token_addr: String,
    pub name: String,
    pub symbol: String,
    pub once_amount: i64,
    pub total_supply: BigDecimal,
    pub total_eth: BigDecimal,
    pub start_time: DateTime<Utc>,
    pub publish_time: DateTime<Utc>,
    pub is_burn_lp_token: bool,
    pub creator_addr: String,
    pub creator_id: String,
    pub transaction_hash: String,
    pub description: String,
    pub image: String,
    pub id: i64,
    pub remark: Option<String>,
    pub update_time: Option<DateTime<Utc>>,
    pub create_time: DateTime<Utc>,
    pub create_by: i64,
    pub update_by: Option<i64>,
    pub is_delete: bool,
}